#!/usr/bin/python3
"""N-queens"""
import sys

if len(sys.argv) != 2:
    print("Usage: nqueens N\n")
    exit(1)
if isinstance(sys.argv[1], int):
    print("N must be a number\n")
    exit(1)
if sys.argv[1] < 4:
    print("N must be at least 4\n")
    exit(1)
